run_modules:
- fastqc
- fastp
- samtools
sp: {}
module_order:
# SR QC Only Order
- fastqc:
    name: FastQC (Raw_Reads)
    path_filters: FETCH_SRA_PE/READ_QC_SR/RAW_FASTQC/*_fastqc.zip
- fastp:
    name: FastP
    path_filters: FETCH_SRA_PE/READ_QC_SR/FASTP/*.json
- fastqc:
    name: FastQC (Final QC Reads)
    path_filters: FETCH_SRA_PE/READ_QC_SR/TRIM_FASTQC/*_fastqc.zip